service: lag-api

provider:
  name: aws
  runtime: nodejs6.10
  region: ${opt:region}
  stage: ${opt:stage}

functions:
  userHandler:
    handler: user/handler.handle
    events:
      - http:
          method: get
          path: users/{userID}
          request:
            parameters:
              paths:
                id: true
    environment:
      ALMA_KEY: ${env:ALMA_API_KEY}
      USER_CACHE_TABLE_NAME: ${self:custom.tableNames.${opt:stage}.userTable}
      USERS_QUEUE_URL: ${self:custom.queueUrls.${opt:stage}.userQueue}

custom:
  tableNames:
    stg:
      userTable: ${env:USER_TABLE_NAME_STG}
    prod:
      userTable: ${env:USER_TABLE_NAME_PROD}
  
  queueUrls:
    stg:
      userQueue: ${env:USER_QUEUE_URL_STG}
    prod:
      userQueue: ${env:USER_QUEUE_URL_PROD}